kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: app1:latest
        imagePullPolicy: Never # Gotcha: Accommodate running the app1:latest local Docker image. Todo: Make imagePullPolicy configurable.
        env:
          - name: ENV
            value: prod
          - name: COLOR
            value: expensiveblue
          - name: PASSWORD
            value: ""
