#!/bin/bash
# Script get-secret simulates getting secrets from some external secrets manager. Then you can get your secret value from hypothetical secrets manager based on secret key, secret id, and secret version.
#
# For example, to get password123 secret value; run the `SECRET=app1-dev VERSION=08aade62 get-secret` command.
#
#
# For simplicity, only input environment variables--not command-line arguments.
#
# SECRET optional, corresponds to your secret ID; for example, app1-dev, or app2-prod. If empty, then print all secrets.
# VERSION optional, corresponds to your server version; for example, 1d137d3c--defaults to latest.
#
# Installation:
#
# To install get-secret command, run the `sudo make install` command.

secret_data="$(docker run --rm -i mikefarah/yq:4 <<'SECRET_DATA'
app1-dev:
  latest:
    PASSWORD: app1-dev-pass-2
    SPAM: eggs
  "1d137d3c":
    PASSWORD: app1-dev-pass-2
    SPAM: eggs
  "62f9d505":
    PASSWORD: app1-dev-pass-1
  "08aade62":
    PASSWORD: password123
app2-dev:
  latest:
    PASSWORD: app2-dev-pass-2
    SPAM: eggs
  9ab33a84:
    PASSWORD: app2-dev-pass-2
    SPAM: eggs
  6dea2e68:
    PASSWORD: app2-dev-pass-1
app1-prod:
  latest:
    PASSWORD: app1-prod-pass-2
    SPAM: eggs
  32c282c4:
    PASSWORD: app1-prod-pass-2
    SPAM: eggs
  063c7855:
    PASSWORD: app1-prod-pass-1
app2-prod:
  latest:
    PASSWORD: app2-prod-pass-2
    SPAM: eggs
  28659e77:
    PASSWORD: app2-prod-pass-2
    SPAM: eggs
  c3729233:
    PASSWORD: app2-prod-pass-1
SECRET_DATA
)"

if [[ -n $SECRET ]]
then
	docker run \
	--env=secret=$SECRET \
	--env=version=${VERSION:-latest} \
	--rm -i \
	mikefarah/yq:4 -oj '.[env(secret)].[env(version)]' <<<"$secret_data"
else
	docker run --rm -i mikefarah/yq:4 -oj <<<"$secret_data"
fi
